# SPDX-FileCopyrightText: 2022 Gregory Clunies <greg@reflekt-ci.com>
#
# SPDX-License-Identifier: Apache-2.0

# Setup for python env using conda:
#   1. Install conda env with poetry dependency
#         conda env update --file ./environment.yml --prune
#   2. Activate the conda env `source activate reflekt-conda` OR `conda activate reflekt-conda`
#   3. Run `poetry install` ... this will install the dependencies from poetry.lock INSIDE the conda env (magic!)
name: reflekt-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python =3.9
  - pip:
    - poetry
