name: Publish Python Package to PyPi

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Publish to PyPi
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Publish package to PyPI
        uses: JRubics/poetry-publish@v1.16
        with:
          python_version: "3.10.7"
          poetry_version: "==1.3.2"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
